import { CategorySchema, GroceryItem, SettingItem } from './schema';

// categories.js
export const categories: CategorySchema[] = [
  { id: 'Fruits', name: 'Fruits', image: require('../assets/images/categories/Fruits.png') },
  { id: 'Vegetables', name: 'Vegetables', image: require('../assets/images/categories/Vegetables.png'), },
  { id: 'Dairy', name: 'Dairy', image: require('../assets/images/categories/Dairy.png') },
  { id: 'Namkeen', name: 'Namkeen', image: require('../assets/images/categories/Snacks.png') },
  { id: 'Snacks', name: 'Snacks', image: require('../assets/images/categories/Chips.png') },
  { id: 'Desserts', name: 'Desserts', image: require('../assets/images/categories/Sweets.png') },
  { id: 'Beverages', name: 'Beverages', image: require('../assets/images/categories/Beverages.png'), },
  { id: 'Meat', name: 'Meat', image: require('../assets/images/categories/bakery.png') },
  { id: 'Condiments', name: 'Condiments', image: require('../assets/images/categories/bakery.png') },
  { id: 'Spreads', name: 'Spreads', image: require('../assets/images/categories/bakery.png') },
];


export const stores = [
  { itemId: '1', itemName: 'Store 1', image: require('../assets/images/categories/Sweets.png') },
  { itemId: '2', itemName: 'Store 2', image: require('../assets/images/categories/Sweets.png') },
  { itemId: '3', itemName: 'Store 3', image: require('../assets/images/categories/Sweets.png') },
  { itemId: '4', itemName: 'Store 4', image: require('../assets/images/categories/Sweets.png') },
];

export const mostOrdered: Record<string, GroceryItem[]> = {
  items: [
    {
      itemId: 'apple',
      brand: "hoppit",
      itemName: 'Apple',
      image: require('../assets/images/categories/Fruits/apple.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 120,
      per: "kg",
      tags: ['fresh', 'organic'],
    },
    {
      itemId: 'pineapple',
      brand: "hoppit",
      itemName: 'pineapple',
      image: require('../assets/images/categories/Fruits/pineapple.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 150,
      per: "kg",
      tags: ['fresh'],
    },
    {
      itemId: 'guava',
      brand: "hoppit",
      itemName: 'guava',
      image: require('../assets/images/categories/Fruits/guava.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 120,
      per: "kg",
      tags: ['fresh'],
    },
    {
      itemId: 'potato',
      brand: "hoppit",
      itemName: 'Potato',
      image: require('../assets/images/categories/Vegetables/potato.png'),
      rating: 4.5,
      quantity: 1,
      price: 30,
      per: "kg",
      time: '10-15 min',
      tags: ['fresh'],
    },
    {
      itemId: 'spinach',
      brand: "hoppit",
      itemName: 'Spinach',
      price: 40,
      per: "Gatthi",
      image: require('../assets/images/categories/Vegetables/spinach.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      tags: ['fresh', 'leafy'],
    },

  ]
}

export const products: Record<string, GroceryItem[]> = {
  fruits: [
    {
      itemId: 'apple',
      brand: "hoppit",
      itemName: 'Apple',
      image: require('../assets/images/categories/Fruits/apple.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 120,
      per: "kg",
      tags: ['fresh', 'organic'],
    },
    {
      itemId: 'banana',
      brand: "hoppit",
      itemName: 'Banana',
      image: require('../assets/images/categories/Fruits/banana.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 60,
      per: "Dozen",
      tags: ['fresh'],
    },
    {
      itemId: 'mango',
      brand: "hoppit",
      itemName: 'mango',
      image: require('../assets/images/categories/Fruits/mango.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 70,
      per: "kg",
      tags: ['fresh', 'seasonal'],
    },
    {
      itemId: 'pineapple',
      brand: "hoppit",
      itemName: 'pineapple',
      image: require('../assets/images/categories/Fruits/pineapple.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 150,
      per: "kg",
      tags: ['fresh'],
    },
    {
      itemId: 'kiwi',
      brand: "hoppit",
      itemName: 'kiwi',
      image: require('../assets/images/categories/Fruits/kiwi.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 90,
      per: "kg",
      tags: ['fresh', 'exotic'],
    },
    {
      itemId: 'guava',
      brand: "hoppit",
      itemName: 'guava',
      image: require('../assets/images/categories/Fruits/guava.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      price: 120,
      per: "kg",
      tags: ['fresh'],
    },
  ],
  vegetables: [
    {
      itemId: 'carrot',
      brand: "hoppit",
      itemName: 'Carrot',
      image: require('../assets/images/categories/Vegetables/carrot.png'),
      price: 60,
      rating: 4.5,
      quantity: 1,
      per: "kg",
      time: '10-15 min',
      tags: ['fresh', 'organic'],
    },
    {
      itemId: 'potato',
      brand: "hoppit",
      itemName: 'Potato',
      image: require('../assets/images/categories/Vegetables/potato.png'),
      rating: 4.5,
      quantity: 1,
      price: 30,
      per: "kg",
      time: '10-15 min',
      tags: ['fresh'],
    },
    {
      itemId: 'broccoli',
      brand: "hoppit",
      itemName: 'Broccoli',
      image: require('../assets/images/categories/Vegetables/broccoli.png'),
      rating: 4.5,
      quantity: 1,
      price: 90,
      per: "kg",
      time: '10-15 min',
      tags: ['fresh', 'organic'],
    },
    {
      itemId: 'spinach',
      brand: "hoppit",
      itemName: 'Spinach',
      price: 40,
      per: "Gatthi",
      image: require('../assets/images/categories/Vegetables/spinach.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      tags: ['fresh', 'leafy'],
    },
    {
      itemId: 'cabbage',
      brand: "hoppit",
      itemName: 'Cabbage',
      price: 60,
      per: "kg",
      image: require('../assets/images/categories/Vegetables/cabbage.png'),
      rating: 4.5,
      quantity: 1,
      time: '10-15 min',
      tags: ['fresh', 'leafy'],
    },
  ],
};

export const settingsData: { General: SettingItem[]; Account: SettingItem[] } = {
  General: [
    { id: 'General', name: 'General', image: "cog-outline", href: '/settings/General' },
    { id: 'Orders', name: 'Orders', image: "receipt-outline", href: '/settings/Orders' },
    { id: 'Login & Password', name: 'Login & Password', image: "key-outline", href: '/settings/LoginPass' },
  ],

  Account: [
    { id: 'Complaints', name: 'Complaints', image: "thumbs-down-outline", href: '/settings/Complaints' },
    {
      id: 'Delete & Deactivate Account',
      name: 'Delete & Deactivate Account',
      image: "person-remove-outline",
      href: '/settings/Account',
    },
  ],
};

